### ISSUE TITLE
Need Navbar for website

### ISSUE THREAD

**Issue by jerrycode06** [CSS-AMU/CSS-AMU-Website#1]
We want to design a navbar for the CSS AMU website. The navbar should be responsive according to mobile and tablet and the design should match with our font and color scheme.

**Comment by nishant803** [comment]
i want to pick this navbar task.

**Comment by jerrycode06** [comment]
Okay, Go ahead

**Comment by ArpitaGupta4086** [comment]
Hey! can i do it?

**Comment by nishant803** [comment]
> Hey! can i do it?

Once i code the navbar you can add your modifications in it

**Comment by Nirodha-Github** [comment]
I have already done and put pull request to merge.
